name: Build Workflow

on:
  workflow_call:
    inputs:
      asset_suffix:
        description: 'Suffix to append to asset names'
        required: false
        default: ''
        type: string
    
jobs:
  build:
    name: Build
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - flag_suffix: 
            build_parameter: --release 
          - flag_suffix: -debug
            build_parameter:
          - flag_suffix: -no-tui
            build_parameter: --release --no-default-features
          - flag_suffix: -debug-no-tui
            build_parameter: --no-default-features

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        run: cargo build ${{ matrix.build_parameter }} --verbose

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: netease-watcher${{ matrix.flag_suffix }}${{ inputs.asset_suffix }}
          path: |
            target/release/*.pdb
            target/release/*.exe
            target/release/*.dll
          compression-level: 9