name: Build Workflow

on:
  workflow_call:
    inputs:
      asset_suffix:
        description: 'Suffix to append to asset names'
        required: false
        default: ''
        type: string
    
jobs:
  build:
    name: Build
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - name: Release with Text UI
            flag_suffix: 
            build_parameter: --release
            target_folder: release
          - name: Debug with Text UI
            flag_suffix: -debug
            build_parameter:
            target_folder: debug
          - name: Release without Text UI
            flag_suffix: -no-tui
            build_parameter: --release --no-default-features
            target_folder: release
          - name: Debug without Text UI
            flag_suffix: -debug-no-tui
            build_parameter: --no-default-features
            target_folder: debug

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        run: cargo build ${{ matrix.build_parameter }} --verbose

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: netease-watcher${{ matrix.flag_suffix }}${{ inputs.asset_suffix }}
          path: |
            target/${{ matrix.target_folder }}/*.pdb
            target/${{ matrix.target_folder }}/*.exe
            target/${{ matrix.target_folder }}/*.dll
          compression-level: 9