name: Build and Release

on:
  release:
    types: [ created ]

permissions:
  contents: write

jobs:
  build:
    uses: ./.github/workflows/build.yml
    
  upload-to-release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      
      - name: Create zip files from artifact folders
        run: |
          mkdir -p releases
          cd artifacts
          for dir in */; do
            if [ -d "$dir" ]; then
              zip -r "../releases/${dir%/}.zip" "$dir"
            fi
          done
          
      - name: Upload artifacts to release
        uses: softprops/action-gh-release@v2
        with:
          files: releases/*
          fail_on_unmatched_files: false